V1
NickShkril/Examine-service pull request #1
Opened 2022-04-16 10:26 UTC by NickShkril

2022-04-17 00:44 UTC, rmuhamedgaliev requested changes
Требуются правки

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/controller/ExamController.java
> +    private final ExaminerService service;
А что буедт если у тебя 2 бина будут этот интерфей реализовыват, что будет? разберись с именованием бинов.

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/controller/JavaQuestionController.java
> +    public JavaQuestionController(QuestionService service) {
А что если у тебя будет не только 1 класс реализующий этот интерфейс, создай и посомтри какую ты ошибку получишь и исправь название бина который инжектишь

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/controller/JavaQuestionController.java
> +   //asdasd
Это еще что?

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/service/JavaQuestionService.java
> +            if (question == null) {
Вижу дублирование, наверно что-то можно сделать

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/service/JavaQuestionService.java
> +            Random random = new Random();
А зачем на каждом вызове метода создавать новый объект рандома? Может можно эффективнее сделать?

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/service/JavaQuestionService.java
> +            return null;
Никогда не возвращай NULL, тебя не поймут. Если ты тут должен вернуть объект то возвращай, если не гарантируешь, либо кидай ошибку либо Optional делай

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/service/JavaQuestionService.java
> +
зачем такое количество разрывов?

2022-04-17 00:44 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/kusrach2/Question.java
> +    public String getQuestion() {
геттеры и сеттеры лучше после конструтора делать и если у тебя полагается менять поля объекта, то лучше финализировать их сразу

2022-04-29 22:47 UTC, OKrylov approved these changes
В целом по работе зачет. Я оставил пару небольших замечаний, на которые стоит обратить внимание, но они не критичны

2022-04-29 22:47 UTC, OKrylov commented on src/main/java/pro/sky/kusrach2/Exception/randomException.java
> +public class randomException extends RuntimeException {
классы именуем с большой буквы

2022-04-29 22:47 UTC, OKrylov commented on src/test/java/pro/sky/kusrach2/ExaminerServiceImplTest.java
> +        out.getQuestions(5);
тест ничего не ассертит. Любой тест должен иметь метод вида assert, чтобы тест прошел или провалился, если функционал не работает

2022-04-29 22:47 UTC, OKrylov commented on src/test/java/pro/sky/kusrach2/JavaQuestionServiceImplTest.java
> +        while (a) {
стоит делать по аналогии с сервисом по сбору вопросов: создать сет и выполнять цикл пока сет не заполнится. При этом стоит пометить тест аннотацией `@Timeout(5)`, чтобы избежать его возможного зацикливания

2023-02-07 08:09 UTC, merged